name: context 

on: [pull_request,push]

jobs:
    check-context:
     runs-on: ubuntu-latest
     
     steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
           fetch-depth: 0

      - name: check for context
        if: ${{ github.event_name=='pull_request'}}
        run: |
          Hi ${{ github.actor }} this is ${{ github.repository }}
          current workflow is ${{ github.workflow }}
          github_action gives ${{ github.action }}
          github base_ref give ${{ github.base_ref}} 

      - name: check for context
        if: ${{ github.event_name=='push'}}
        run: |
          Hi ${{ github.actor }} this is ${{ github.repository }}
          current workflow is ${{ github.workflow }}
          

