name: Files Changed

on: [pull_request, push]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout ${{ github.repository }} repository"

      uses: "actions/checkout@v3"
      with:
        fetch-depth: 0

    - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v12
        id: verify_changed_files
        with:
          files: |
            .github/workflows

    - name: Files changed
        if: steps.verify_changed_files.outputs.files_changed == 'true'
        run: |
          Hello ${{ github.actor }}, a file has uncommitted changes
        
    - name: Comment if there are any changes in the files
        uses: "thollander/actions-comment-pull-request@v2"
        with:
          message: |
          Hi ${{ github.actor }} 
          The following files have been changed in ${{github.repository }}