name: Install node

on: [pull_request]

jobs: 
  builds:
    runs-on: ubuntu-latest

    steps:
      - name: Install npm
        uses: "actions/checkout@v3"
        uses: "actions/setup-node@v3"
        with:
           node-version: 16
        package-lock.json:
            npm install
        yarn.lock:
            yarn --check-files --frozen-lockfile --non-interactive




