name: set up the environment for Node JS

on: [pull_request]

jobs: 
  builds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install

      - name: Creating a build directory
        run: npm run build